安装visdom：
pip install visdom

启动服务器（可能在screen或者tmux中）：
python -m visdom.server

一旦启动服务器，您就可以通过在浏览器中输入 http://localhost:8097 访问Visdom，localhost可以换成您的托管地址。

If the above does not work, try using an SSH tunnel to your server by 把底下这一行加到本地的 ~/.ssh/config 中: 
LocalForward 127.0.0.1:8097 127.0.0.1:8097.


github：https://github.com/facebookresearch/visdom
翻译版：http://blog.csdn.net/u012436149/article/details/69389610?utm_source=gold_browser_extension

In [3]:
#visdom 学习笔记
import visdom
import numpy as np
viz = visdom.Visdom()
#画一个文本框
textwindow = viz.text('Hello, world!')

In [52]:
#画一张图 （CxHxW）
viz.image(np.ones((3, 10, 10)))
#画一张噪声图
viz.image(
    np.random.rand(3, 512, 256),
    opts=dict(title='噪点', caption='好噪啊。'),
)

Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [51]:
viz=visdom.Visdom("wcd")

In [6]:
y = np.random.rand(10)
print(y.mean())
print(y)
print(y + 1.5)
print((y+1.5).astype(int))
print((y+0.5).astype(int))
print(y.astype(int))

0.284313680011
[ 0.16825475  0.07546459  0.34128893  0.1026385   0.29419     0.20318261
  0.18331875  0.40251968  0.60888282  0.46339618]
[ 1.66825475  1.57546459  1.84128893  1.6026385   1.79419     1.70318261
  1.68331875  1.90251968  2.10888282  1.96339618]
[1 1 1 1 1 1 1 1 2 1]
[0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0]


In [7]:
Y = np.random.rand(100)
#2d散点图
viz.scatter(
    #样本点有100个2维样本
    X=np.random.rand(100, 2), 
    #100个样本的标签是Y（>1的整数）
    Y=(Y[Y > 0] + 1.5).astype(int),
    opts=dict(
        legend=['Apples', 'Pears'],
        xtickmin=-5,
        xtickmax=5,
        xtickstep=0.5,
        #横坐标从-5~5，格子跨度0.5
        ytickmin=-5,
        ytickmax=5,
        ytickstep=0.1,
        #纵坐标从-5~5，格子跨度1
        markersymbol='cross-thin-open',
        title='2d散点图',
    ),
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [8]:
#3d散点图
viz.scatter(
    X=np.random.rand(100, 3),
    Y=(Y + 1.5).astype(int),
    opts=dict(
        legend=['Men', 'Women'],
        markersize=5,
        title='3d散点图',
    )
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [9]:
# 2D scatterplot with custom intensities (red channel)
viz.scatter(
    X=np.random.rand(255, 2),
    Y=(np.random.rand(255) + 1.5).astype(int),
    opts=dict(
        markersize=10,
        #marker的颜色随机（0~255的随机数 大小为2x3）
        markercolor=np.random.randint(0, 255, (2, 3,)),
    ),
)
print(np.random.randint(0, 255, (2, 3,)))

Exception in user code:
------------------------------------------------------------
[[189 126  16]
 [  0 108 125]]


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/wcd/app/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/wcd/app/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string


In [10]:
# 2D scatter plot with custom colors per label:
viz.scatter(
    X=np.random.rand(255, 2),
    Y=(np.random.randn(255) > 0) + 1,
    opts=dict(
        markersize=10,
        markercolor=np.floor(np.random.random((2, 3)) * 255),
    ),
)
print(np.floor(np.random.random((2, 3)) * 255))

Exception in user code:
------------------------------------------------------------
[[  27.  214.   46.]
 [  20.  183.  134.]]


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/wcd/app/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/wcd/app/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string


In [11]:
win = viz.scatter(
    X=np.random.rand(255, 2),
    opts=dict(
        markersize=10,
        markercolor=np.random.randint(0, 255, (255, 3,)),
    ),
)
print(np.random.randint(0, 255, (255, 3,)).shape)

Exception in user code:
------------------------------------------------------------
(255, 3)


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

In [12]:
# add new trace to scatter plot
viz.updateTrace(
    X=np.random.rand(1),
    Y=np.random.rand(1),
    win=win,
    name='new_trace',
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [13]:
img = np.array(Image.open('/home/wcd/Projects/Pytorch-examples/fast_neural_style/images/yang/t2.bmp').convert('YCbCr'))
print(img.shape)
a = Image.fromarray(img[:,:,0],'L')
b = Image.fromarray(img[:,:,1],'L')
c = Image.fromarray(img[:,:,2],'L')
Image.merge('YCbCr',[a,b,c]).convert('RGB')

NameError: name 'Image' is not defined

In [14]:
# line plots
#一条随机取值线
viz.line(Y=np.random.rand(10))
#一条函数线
Y = np.linspace(-5, 5, 100)
viz.line(
    Y=np.column_stack((Y * Y, np.sqrt(Y + 5))),
    X=np.column_stack((Y, Y)),
    opts=dict(markers=False),
)

Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [15]:
# line updates
win = viz.line(
    #一个column一条线
    #X：坐标轴 Y：取值
    #X=np.column_stack((np.arange(0, 10), np.arange(0, 10))),
    Y=np.column_stack((np.linspace(5, 10, 10), np.linspace(5, 10, 10) + 5)),
    opts=dict(title='线图'),
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

In [16]:
#第一种update方式：在原win窗口直接加点，然后连线，如果X比上一次的坐标要小，则出现一条右往左线段
viz.line(
    #must specify x-values for line update
    X=np.column_stack((np.arange(12, 22), np.arange(11, 21))),
    Y=np.column_stack((np.linspace(5, 10, 10), np.linspace(5, 10, 10) + 5)),
    #制定了update源是win这个pane
    win=win,
    update='append',
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [17]:
np.column_stack((np.arange(12, 22), np.arange(11, 21))).shape

(10, 2)

In [18]:
#第二种update方式：在x位置加上y值，连成线 最好一次一条线
viz.updateTrace(
    X=np.arange(21, 30),
    Y=np.arange(1, 10),
    win=win,
    name='2'
)
viz.updateTrace(
    X=np.arange(1, 10),
    Y=np.arange(11, 20),
    win=win,
    name='4'
)

Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [19]:
viz.updateTrace(
    X=np.arange(1, 10),
    Y=np.arange(11, 20),
    win=win,
    name='4'
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [20]:
Y = np.linspace(0, 4, 200)
win = viz.line(
    Y=np.column_stack((np.sqrt(Y), np.sqrt(Y) + 2)),
    X=np.column_stack((Y, Y)),
    opts=dict(
        fillarea=True,
        legend=False,
        width=400,
        height=400,
        xlabel='Time',
        ylabel='Volume',
        ytype='log',
        title='Stacked area plot',
        marginleft=30,
        marginright=30,
        marginbottom=80,
        margintop=30,
    ),
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

In [21]:
# bar plots
#普通条形图：像直方图
viz.bar(X=np.random.rand(20))
#叠起来的条形图
viz.bar(
    X=np.abs(np.random.rand(5, 3)),
    opts=dict(
        stacked=True,
        legend=['Facebook', 'Google', 'Twitter'],
        rownames=['2012', '2013', '2014', '2015', '2016']
    )
)
#分组的条形图
viz.bar(
    X=np.random.rand(20, 3),
    opts=dict(
        stacked=False,
        legend=['The Netherlands', 'France', 'United States']
    )
)

Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [22]:
# histogram
viz.histogram(X=np.random.rand(10000), opts=dict(numbins=20))

# heatmap
viz.heatmap(
    X=np.outer(np.arange(1, 6), np.arange(1, 11)),
    opts=dict(
        columnnames=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
        rownames=['y1', 'y2', 'y3', 'y4', 'y5'],
        colormap='Electric',
    )
)

Exception in user code:
------------------------------------------------------------
Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [23]:
# boxplot 统计量方框
X = np.random.rand(1000, 2)
#print(X)
X[:, 1] += 2
#print(X)
viz.boxplot(
    X=X,
    opts=dict(legend=['Men', 'Women'])
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [24]:
# contour 等高线
x = np.tile(np.arange(1, 101), (100, 1))
y = x.transpose()
X = np.exp((((x - 50) ** 2) + ((y - 50) ** 2)) / -(20.0 ** 2))
viz.contour(X=X, opts=dict(colormap='Viridis'))

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

In [25]:
import math
# stemplot
Y = np.linspace(0, 2 * math.pi, 70)
X = np.column_stack((np.sin(Y), np.cos(Y)))
win = viz.stem(
    X=X,
    Y=Y,
    opts=dict(legend=['Sine', 'Cosine'])
)

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

In [26]:
# surface 表面
viz.surf(X=X, opts=dict(colormap='Hot'))

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

In [27]:
import torch

In [28]:
from torch.autograd import Variable
import numpy as np
x=Variable(torch.Tensor(np.random.randn(1,1)))
m=x.mean()
print(x.data)
print(x.data[0])
print(x.data.numpy())
print(x.data[0].numpy())
#viz.line(Y=x.data.numpy())
viz=visdom.Visdom("wcd")
viz.line(
    X=np.ones(1),
         Y=x.data[0].numpy()
        )


-0.3490
[torch.FloatTensor of size 1x1]


-0.3490
[torch.FloatTensor of size 1]

[[-0.34896106]]
[-0.34896106]
Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [29]:
from PIL import Image,ImageFilter
from torchvision import transforms
l = Image.open("/home/wcd/Projects/Pytorch-examples/fast_neural_style/images/style-images/flowers.bmp").convert('L')
img = Image.merge("RGB", (l, l, l))
transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Lambda(lambda x_HR: x_HR.mul(255))
    ])
imgtensor = transform(img)
viz.image(
        imgtensor,
        win=win,
        opts=dict(title='噪点', caption='好噪啊。'),
    )

Exception in user code:
------------------------------------------------------------


Traceback (most recent call last):
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/visdom/__init__.py", line 240, in _send
    data=json.dumps(msg),
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/home/wcd/app/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No con

False

In [30]:
viz=visdom.Visdom()
X=np.array([1])
Y=torch.ones(1).numpy()
print(X.shape)
print(Y.shape)
#X.ndim
viz.line(
    X=X,
    Y=Y,
    # 制定了update源是win这个pane
)

(1,)
(1,)


'pane_35924315b75e74'

In [31]:
x = torch.ones(3,10,10)
y=x.repeat(1, 1,1,1)
y.squeeze(0)


(0 ,.,.) = 
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1

(1 ,.,.) = 
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1

(2 ,.,.) = 
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1   1   1   1   1   1   1
   1   1   1   1  

In [32]:
def drawloss(viz,loss_win,batch_id,loss):
    if loss_win is None:
        loss_win = viz.line(
            # X=np.column_stack((batch_id, batch_id, batch_id)),
            X=np.column_stack((batch_id, batch_id)),
            Y=np.column_stack(loss),
            opts=dict(
                markers=False,
                legend=['train','val'],
            ),
        )
    else:
        loss_win = viz.line(
            # must specify x_HR-values for line update
            X=np.column_stack((batch_id, batch_id)),
            Y=np.column_stack(loss),
            # 制定了update源是win这个pane
            win=loss_win,
            update='append',
            opts=dict(
                markers=False,
                legend=['train','val'],
            ),
        )
    return loss_win

In [33]:
import numpy as np
import visdom
viz=visdom.Visdom()
loss_win=None

In [34]:
loss_win = drawloss(viz,loss_win,3,(3.3,5.4))

In [35]:
np.array([[2.4],[3.6]])

array([[ 2.4],
       [ 3.6]])

In [36]:
np.array([2.4,3.6])

array([ 2.4,  3.6])

In [37]:
np.column_stack([2.4,3.6])

array([[ 2.4,  3.6]])

In [38]:
def normalize_batch(batch):
    # normalize using imagenet mean and std
    mean = batch.data.new(batch.data.size())
    std = batch.data.new(batch.data.size())
    mean[:, 0, :, :] = 0.485
    mean[:, 1, :, :] = 0.456
    mean[:, 2, :, :] = 0.406
    std[:, 0, :, :] = 0.229
    std[:, 1, :, :] = 0.224
    std[:, 2, :, :] = 0.225
    batch = torch.div(batch, 255.0)
    batch -= Variable(mean,volatile=False)
    batch /= Variable(std,volatile=False)
    return batch

def unnormalize_batch(batch):
    mean = batch.data.new(batch.data.size())
    std = batch.data.new(batch.data.size())
    mean[:, 0, :, :] = 0.485
    mean[:, 1, :, :] = 0.456
    mean[:, 2, :, :] = 0.406
    std[:, 0, :, :] = 0.229
    std[:, 1, :, :] = 0.224
    std[:, 2, :, :] = 0.225
    batch = torch.mul(batch,Variable(std,volatile=False))
    batch += Variable(mean,volatile=False)
    batch = torch.mul(batch, 255.0)
    return batch

In [39]:
from torch.autograd import Variable
import torch

In [40]:
tensor = torch.from_numpy(np.random.rand(2,3,5,5))
tensor = tensor.mul_(255).clamp(0,255)
print(tensor)


(0 ,0 ,.,.) = 
  188.7007  187.2514  175.6069  246.0495  241.6521
  192.8040  251.4220  104.6568  226.2137  241.1339
  122.5694   39.1596   39.2462  113.6772  143.4856
   40.4655  174.3336  164.4531  179.6548  250.0267
   48.8512   57.1644  193.7050  194.3627   42.6835

(0 ,1 ,.,.) = 
   88.2197   52.2057  158.3724   98.8203  210.1734
  215.9200  198.3512   44.5079   99.8735   52.7870
  186.2892   29.0450  201.3943  253.1179   42.8052
   40.2775  202.1394   69.6752   10.7073   65.3108
  247.3227  134.3512  161.4795  110.2462   74.3193

(0 ,2 ,.,.) = 
   62.7139  183.7134  194.2427  179.7529  223.2904
  157.1564  192.7075   21.9927  175.3250   85.4560
  121.5404  238.0463  143.9700  214.2897  132.4322
  251.3968   49.6626  253.6863  244.7900  172.7228
  112.6649  236.7970  101.6001   94.7343  154.0119

(1 ,0 ,.,.) = 
  109.3257  186.9758  188.5164   66.3200   63.4892
   64.5432    0.0222  223.6622  216.6056   93.3440
  141.3144  177.4105  169.5902  226.7305   66.2362
   44.0116  204.32

In [41]:
vt = Variable(tensor,requires_grad = True)
norm = normalize_batch(vt)
print(norm)

Variable containing:
(0 ,0 ,.,.) = 
  1.1135  1.0887  0.8893  2.0956  2.0203
  1.1838  2.1876 -0.3257  1.7560  2.0115
 -0.0189 -1.4473 -1.4458 -0.1712  0.3393
 -1.4249  0.8675  0.6983  0.9586  2.1637
 -1.2813 -1.1390  1.1992  1.2105 -1.3870

(0 ,1 ,.,.) = 
 -0.4913 -1.1217  0.7369 -0.3057  1.6438
  1.7444  1.4368 -1.2565 -0.2872 -1.1116
  1.2257 -1.5272  1.4901  2.3956 -1.2863
 -1.3306  1.5031 -0.8159 -1.8483 -0.8923
  2.2942  0.3164  0.7913 -0.1056 -0.7346

(0 ,2 ,.,.) = 
 -0.7114  1.3975  1.5810  1.3285  2.0873
  0.9347  1.5543 -1.4211  1.2513 -0.3150
  0.3139  2.3445  0.7048  1.9305  0.5037
  2.5772 -0.9389  2.6171  2.4620  1.2060
  0.1592  2.3227 -0.0336 -0.1533  0.8799

(1 ,0 ,.,.) = 
 -0.2457  1.0840  1.1104 -0.9822 -1.0307
 -1.0126 -2.1175  1.7123  1.5914 -0.5194
  0.3021  0.9202  0.7863  1.7648 -0.9836
 -1.3642  1.3810 -1.2741  0.9319 -0.8283
 -1.7628 -1.4594  1.8210  0.2891  2.0780

(1 ,1 ,.,.) = 
 -0.0371  0.7625  2.0563  0.8417 -1.7690
  2.2520  1.2653  0.9132 -0.2218  2.043

In [42]:
unorm = unnormalize_batch(norm)
print(unorm)

Variable containing:
(0 ,0 ,.,.) = 
  188.7007  187.2514  175.6069  246.0495  241.6521
  192.8040  251.4220  104.6568  226.2137  241.1339
  122.5694   39.1596   39.2462  113.6772  143.4856
   40.4655  174.3336  164.4531  179.6548  250.0267
   48.8512   57.1644  193.7050  194.3627   42.6835

(0 ,1 ,.,.) = 
   88.2197   52.2057  158.3724   98.8203  210.1734
  215.9200  198.3512   44.5079   99.8735   52.7870
  186.2892   29.0450  201.3943  253.1179   42.8052
   40.2775  202.1394   69.6752   10.7073   65.3108
  247.3227  134.3512  161.4795  110.2462   74.3193

(0 ,2 ,.,.) = 
   62.7139  183.7134  194.2427  179.7529  223.2904
  157.1564  192.7075   21.9927  175.3250   85.4560
  121.5404  238.0463  143.9700  214.2897  132.4322
  251.3968   49.6626  253.6863  244.7900  172.7228
  112.6649  236.7970  101.6001   94.7343  154.0119

(1 ,0 ,.,.) = 
  109.3257  186.9758  188.5164   66.3200   63.4892
   64.5432    0.0222  223.6622  216.6056   93.3440
  141.3144  177.4105  169.5902  226.7305   66.236

In [43]:
torch.add(vt,-1*unorm)

Variable containing:
(0 ,0 ,.,.) = 
1.00000e-14 *
   0.0000  0.0000  0.0000  0.0000  2.8422
   0.0000  0.0000  0.0000  0.0000  2.8422
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000

(0 ,1 ,.,.) = 
1.00000e-14 *
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.7105
   0.0000  0.0000  0.0000  2.8422  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000

(0 ,2 ,.,.) = 
1.00000e-14 *
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000

(1 ,0 ,.,.) = 
1.00000e-14 *
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000
   0.0000  0.0000  0.0000  0.0000  0.0000

(1 ,1 ,.,.) = 
1.00

In [44]:
import torch
import torch.nn.init

class TransformerNet(torch.nn.Module):
    def __init__(self, mode='RGB'):
        super(TransformerNet, self).__init__()
        if mode is 'Y' :
            channel = 1
        else :
            channel = 3
        # Initial convolution layers
        self.conv1 = ConvLayer(channel, 32, kernel_size=9, stride=1)
        self.in1 = torch.nn.InstanceNorm2d(32, affine=True)
        self.conv2 = ConvLayer(32, 64, kernel_size=3, stride=2)
        self.in2 = torch.nn.InstanceNorm2d(64, affine=True)
        self.conv3 = ConvLayer(64, 128, kernel_size=3, stride=2)
        self.in3 = torch.nn.InstanceNorm2d(128, affine=True)
        # Residual layers
        self.res1 = ResidualBlock(128)
        self.res2 = ResidualBlock(128)
        self.res3 = ResidualBlock(128)
        self.res4 = ResidualBlock(128)
        self.res5 = ResidualBlock(128)
        # Conv+PS upsampling Layers
        self.ps1 = ConvPSLayer(128, 64, kernel_size=3, stride=1, upsample=2)
        self.in4 = torch.nn.InstanceNorm2d(64, affine=True)
        self.ps2 = ConvPSLayer(64, 32, kernel_size=3, stride=1, upsample=2)
        self.in5 = torch.nn.InstanceNorm2d(32, affine=True)
        self.conv4 = ConvLayer(32, channel, kernel_size=3, stride=1)
        # Non-linearities
        self.relu = torch.nn.ReLU()


    def forward(self, X):
        y = self.relu(self.in1(self.conv1(X)))
        y = self.relu(self.in2(self.conv2(y)))
        y = self.relu(self.in3(self.conv3(y)))
        y = self.res1(y)
        y = self.res2(y)
        y = self.res3(y)
        y = self.res4(y)
        y = self.res5(y)
        y = self.relu(self.in4(self.ps1(y)))
        y = self.relu(self.in5(self.ps2(y)))
        y = self.conv4(y)
        #y += X
        return y


class ConvLayer(torch.nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        super(ConvLayer, self).__init__()
        reflection_padding = kernel_size // 2
        self.reflection_pad = torch.nn.ReflectionPad2d(reflection_padding)
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride)


    def forward(self, x):
        #out = self.reflection_pad(x)
        out = self.conv2d(x)
        return out


class ResidualBlock(torch.nn.Module):
    """ResidualBlock
    introduced in: https://arxiv.org/abs/1512.03385
    recommended architecture: http://torch.ch/blog/2016/02/04/resnets.html
    """

    def __init__(self, channels):
        super(ResidualBlock, self).__init__()
        self.conv1 = ConvLayer(channels, channels, kernel_size=3, stride=1)
        self.in1 = torch.nn.InstanceNorm2d(channels, affine=True)
        self.conv2 = ConvLayer(channels, channels, kernel_size=3, stride=1)
        self.in2 = torch.nn.InstanceNorm2d(channels, affine=True)
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        residual = x
        out = self.relu(self.in1(self.conv1(x)))
        out = self.in2(self.conv2(out))
        out = out + residual
        return out


class UpsampleConvLayer(torch.nn.Module):
    """UpsampleConvLayer
    Upsamples the input and then does a convolution. This method gives better results
    compared to ConvTranspose2d.
    ref: http://distill.pub/2016/deconv-checkerboard/
    """

    def __init__(self, in_channels, out_channels, kernel_size, stride, upsample=None):
        super(UpsampleConvLayer, self).__init__()
        self.upsample = upsample
        if upsample:
            self.upsample_layer = torch.nn.UpsamplingNearest2d(scale_factor=upsample)
        reflection_padding = kernel_size // 2
        self.reflection_pad = torch.nn.ReflectionPad2d(reflection_padding)
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride)

    def forward(self, x):
        x_in = x
        if self.upsample:
            x_in = self.upsample_layer(x_in)
        #out = self.reflection_pad(x_in)
        out = self.conv2d(x_in)
        return out


class ConvPSLayer(torch.nn.Module):
    """
    conv of (in,outxuxu,k,s)
    follow by
    pixel shuffle of scalling factor (u)
    output is (bs out hxu wxu)
    """

    def __init__(self, in_channels, out_channels, kernel_size, stride, upsample=None):
        super(ConvPSLayer, self).__init__()
        self.upsample = upsample
        if upsample:
            self.pixelshuffle_layer = torch.nn.PixelShuffle(upsample)
        reflection_padding = kernel_size // 2
        self.reflection_pad = torch.nn.ReflectionPad2d(reflection_padding)
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels*(upsample**2), kernel_size, stride)

    def forward(self, x):

        #out = self.reflection_pad(x)
        out = self.conv2d(x)
        if self.upsample:
            out = self.pixelshuffle_layer(out)
        return out

In [45]:
up = UpsampleConvLayer(4, 4, 3, 1, upsample=2).cuda()
sp = ConvPSLayer(4, 4, 3, 1, upsample=2).cuda()
cv = ConvLayer(4, 4, kernel_size=3, stride=1).cuda()

In [46]:
v = Variable(torch.from_numpy(np.random.rand(2,4,10,10))).cuda()

In [47]:
div2 = cv(cv(v))
print(div2.size())
print(up(up(div2)).size())

print(str(v.size())+"conv: "+str(cv(v).size()))

RuntimeError: Input type (Double) and weight type (Float) should be the same

In [48]:
import numpy as np
num=set([0,1,4,2])
print(3 in num)

False


In [49]:
blocknum1 = 12

In [50]:
for latter in range(blocknum1//2,blocknum1,1):
    former = blocknum1-1-latter
    if former in num and former is not latter:
        print(str(former)+":"+str(latter))

4:7
2:9
1:10
0:11
